import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Client } from "@notionhq/client";
import { NotionBlock, Render } from "@9gustin/react-notion-render";

type CompanyProps = {
	blocks: NotionBlock[];
};

const Company: NextPage<CompanyProps> = ({ blocks }) => (
	<>
		<Head>
			<title>Company name</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div className="container mx-auto p-16">
			<h1 className="text-4xl mb-4">Companies Reviews</h1>
			<p className="text-2xl text-gray-800">
				Here you can find all the companies I worked for and my honest reviews
			</p>
			<Render blocks={blocks} />
		</div>
	</>
);

export const getStaticPaths: GetStaticPaths = () => {
	return {
		fallback: true,
		paths: [],
	};
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
	const notion = new Client({ auth: process.env.NOTION_KEY });
	const companyId = params!.slug;

	if (!process.env.NOTION_DATABASE_ID) {
		console.log("Notion Database ID is required");
		return {
			notFound: true,
		};
	}

	if (!companyId) {
		return {
			notFound: true,
		};
	}

	const blocks = await notion.blocks.children.list({
		block_id: companyId as string,
	});

	return {
		props: {
			blocks: blocks.results,
		},
		revalidate: 5,
	};
};

export default Company;
