import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Client } from "@notionhq/client";
import { TCompany } from "typings";
import Header from "components/Header";
import Companies from "components/Companies";

type HomeProps = {
	data: TCompany[];
};

const Home: NextPage<HomeProps> = ({ data }) => (
	<>
		<Head>
			<title>Companies Reviews</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div className="container mx-auto p-16">
			<Header />
			<Companies data={data} />
		</div>
	</>
);

export const getStaticProps: GetStaticProps = async () => {
	const notion = new Client({ auth: process.env.NOTION_KEY });

	if (!process.env.NOTION_DATABASE_ID) {
		console.log("Notion Database ID is required");
		return {
			notFound: true,
		};
	}

	const data = await notion.databases.query({
		database_id: process.env.NOTION_DATABASE_ID,
	});

	return {
		props: {
			data: data.results,
		},
		revalidate: 5,
	};
};

export default Home;
